### **FILE FOR THE DATA TESTING**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pandas.api import types as pdt

In [2]:
Kepler_data=pd.read_csv('C:/Users/Acer/OneDrive/Documents/nasa_space apps/data/cumulative_2025.10.01_04.13.28.csv')

In [3]:

pd.set_option('display.max_columns',None)
Kepler_data.head()

,loc_rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,koi_impact,koi_impact_err1,koi_impact_err2,koi_duration,koi_duration_err1,koi_duration_err2,koi_depth,koi_depth_err1,koi_depth_err2,koi_prad,koi_prad_err1,koi_prad_err2,koi_teq,koi_teq_err1,koi_teq_err2,koi_insol,koi_insol_err1,koi_insol_err2,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_steff_err1,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,-0.002160,0.146,0.318,-0.146,2.95750,0.08190,-0.08190,615.8,19.5,-19.5,2.26,0.26,-0.15,793.0,NaN,NaN,93.59,29.45,-16.65,35.8,1.0,q1_q17_dr25_tce,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,-0.003520,0.586,0.059,-0.443,4.50700,0.11600,-0.11600,874.8,35.5,-35.5,2.83,0.32,-0.19,443.0,NaN,NaN,9.11,2.87,-1.62,25.8,2.0,q1_q17_dr25_tce,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,-0.000581,0.969,5.126,-0.077,1.78220,0.03410,-0.03410,10829.0,171.0,-171.0,14.60,3.92,-1.31,638.0,NaN,NaN,39.30,31.04,-10.49,76.3,1.0,q1_q17_dr25_tce,5853.0,158.0,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,1.276,0.115,-0.092,2.40641,0.00537,-0.00537,8079.2,12.8,-12.8,33.46,8.50,-2.83,1395.0,NaN,NaN,891.96,668.95,-230.35,505.6,1.0,q1_q17_dr25_tce,5805.0,157.0,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,-0.001130,0.701,0.235,-0.478,1.65450,0.04200,-0.04200,603.3,16.9,-16.9,2.75,0.88,-0.35,1406.0,NaN,NaN,926.16,874.33,-314.24,40.9,1.0,q1_q17_dr25_tce,6031.0,169.0,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [4]:
Kepler_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 50 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   loc_rowid          9564 non-null   int64
 1   kepid              9564 non-null   int64
 2   kepoi_name         9564 non-null   object
 3   kepler_name        2747 non-null   object
 4   koi_disposition    9564 non-null   object
 5   koi_pdisposition   9564 non-null   object
 6   koi_score          8054 non-null   float64
 7   koi_fpflag_nt      9564 non-null   int64
 8   koi_fpflag_ss      9564 non-null   int64
 9   koi_fpflag_co      9564 non-null   int64
 10  koi_fpflag_ec      9564 non-null   int64
 11  koi_period         9564 non-null   float64
 12  koi_period_err1    9110 non-null   float64
 13  koi_period_err2    9110 non-null   float64
 14  koi_time0bk        9564 non-null   float64
 15  koi_time0bk_err1   9110 non-null   float64
 16  koi_time0bk_err2   9110 non-null   float64
 17  koi_impact         9201 non-null   float64
 18  koi_impact_err1    9110 non-null   float64
 19  koi_impact_err2    9110 non-null   float64
 20  koi_duration       9564 non-null   float64
 21  koi_duration_err1  9110 non-null   float64
 22  koi_duration_err2  9110 non-null   float64
 23  koi_depth          9201 non-null   float64
 24  koi_depth_err1     9110 non-null   float64
 25  koi_depth_err2     9110 non-null   float64
 26  koi_prad           9201 non-null   float64
 27  koi_prad_err1      9201 non-null   float64
 28  koi_prad_err2      9201 non-null   float64
 29  koi_teq            9201 non-null   float64
 30  koi_teq_err1       0 non-null      float64
 31  koi_teq_err2       0 non-null      float64
 32  koi_insol          9243 non-null   float64
 33  koi_insol_err1     9243 non-null   float64
 34  koi_insol_err2     9243 non-null   float64
 35  koi_model_snr      9201 non-null   float64
 36  koi_tce_plnt_num   9218 non-null   float64
 37  koi_tce_delivname  9218 non-null   object
 38  koi_steff          9201 non-null   float64
 39  koi_steff_err1     9096 non-null   float64
 40  koi_steff_err2     9081 non-null   float64
 41  koi_slogg          9201 non-null   float64
 42  koi_slogg_err1     9096 non-null   float64
 43  koi_slogg_err2     9096 non-null   float64
 44  koi_srad           9201 non-null   float64
 45  koi_srad_err1      9096 non-null   float64
 46  koi_srad_err2      9096 non-null   float64
 47  ra                 9564 non-null   float64
 48  dec                9564 non-null   float64
 49  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(6), object(5)
memory usage: 3.6+ MB

In [5]:
Kepler_data['koi_disposition'].unique()

array(['CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE'], dtype=object)

In [6]:
Kepler_data.isnull().mean()*100

loc_rowid              0.000000
kepid                  0.000000
kepoi_name             0.000000
kepler_name           71.277708
koi_disposition        0.000000
koi_pdisposition       0.000000
koi_score             15.788373
koi_fpflag_nt          0.000000
koi_fpflag_ss          0.000000
koi_fpflag_co          0.000000
koi_fpflag_ec          0.000000
koi_period             0.000000
koi_period_err1        4.746968
koi_period_err2        4.746968
koi_time0bk            0.000000
koi_time0bk_err1       4.746968
koi_time0bk_err2       4.746968
koi_impact             3.795483
koi_impact_err1        4.746968
koi_impact_err2        4.746968
koi_duration           0.000000
koi_duration_err1      4.746968
koi_duration_err2      4.746968
koi_depth              3.795483
koi_depth_err1         4.746968
koi_depth_err2         4.746968
koi_prad               3.795483
koi_prad_err1          3.795483
koi_prad_err2          3.795483
koi_teq                3.795483
koi_teq_err1         100.000000
koi_teq_err2         100.000000
koi_insol              3.356336
koi_insol_err1         3.356336
koi_insol_err2         3.356336
koi_model_snr          3.795483
koi_tce_plnt_num       3.617733
koi_tce_delivname      3.617733
koi_steff              3.795483
koi_steff_err1         4.893350
koi_steff_err2         5.050188
koi_slogg              3.795483
koi_slogg_err1         4.893350
koi_slogg_err2         4.893350
koi_srad               3.795483
koi_srad_err1          4.893350
koi_srad_err2          4.893350
ra                     0.000000
dec                    0.000000
koi_kepmag             0.010456
dtype: float64

In [7]:
Candidate_Data=Kepler_data[Kepler_data['koi_disposition']=='CANDIDATE']

In [8]:

safe_features = [
    "koi_period",
    "koi_duration",
    "koi_depth",
    "koi_model_snr",
    "koi_prad",
    "koi_steff",
    "koi_srad",
    "koi_disposition"
]


Kepler_data=Kepler_data[safe_features]
Candidate_Data=Candidate_Data[safe_features]

In [9]:
Kepler_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   koi_period       9564 non-null   float64
 1   koi_duration     9564 non-null   float64
 2   koi_depth        9201 non-null   float64
 3   koi_model_snr    9201 non-null   float64
 4   koi_prad         9201 non-null   float64
 5   koi_steff        9201 non-null   float64
 6   koi_srad         9201 non-null   float64
 7   koi_disposition  9564 non-null   object
dtypes: float64(7), object(1)
memory usage: 597.9+ KB

In [10]:
Kepler_data=Kepler_data.dropna()

In [11]:
Kepler_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9201 entries, 0 to 9563
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   koi_period       9201 non-null   float64
 1   koi_duration     9201 non-null   float64
 2   koi_depth        9201 non-null   float64
 3   koi_model_snr    9201 non-null   float64
 4   koi_prad         9201 non-null   float64
 5   koi_steff        9201 non-null   float64
 6   koi_srad         9201 non-null   float64
 7   koi_disposition  9201 non-null   object
dtypes: float64(7), object(1)
memory usage: 646.9+ KB

In [12]:
Kepler_data['koi_disposition'].value_counts()

koi_disposition
FALSE POSITIVE    4582
CONFIRMED         2744
CANDIDATE         1875
Name: count, dtype: int64

In [13]:
Candidate_Data=Candidate_Data.reset_index(drop='original')

In [14]:
Candidate_Data.head()

,koi_period,koi_duration,koi_depth,koi_model_snr,koi_prad,koi_steff,koi_srad,koi_disposition
0,19.899140,1.7822,10829.0,76.3,14.60,5853.0,0.868,CANDIDATE
1,40.419504,3.3620,6256.0,36.9,7.51,5446.0,0.781,CANDIDATE
2,7.240661,0.5580,556.4,13.7,19.45,5005.0,0.765,CANDIDATE
3,3.435916,3.1330,23.2,8.7,0.55,5779.0,1.087,CANDIDATE
4,10.181584,3.5089,5741.1,183.6,7.73,5988.0,0.836,CANDIDATE

In [15]:
mask = Kepler_data['koi_disposition'].astype(str).str.strip().str.upper() != 'CANDIDATE'
Kepler_data = Kepler_data.loc[mask].reset_index(drop=True)

print("Remaining rows:", len(Kepler_data))
print(Kepler_data['koi_disposition'].value_counts())

Remaining rows: 7326
koi_disposition
FALSE POSITIVE    4582
CONFIRMED         2744
Name: count, dtype: int64

In [16]:
Kepler_data['koi_disposition']=Kepler_data['koi_disposition'].map({
    'CONFIRMED':0,
    'FALSE POSITIVE':1
})

In [17]:
Kepler_data['koi_disposition'].unique()

array([0, 1])

In [18]:
Kepler_data.to_csv('Training_data.csv',index=False)

In [19]:
Candidate_Data.to_csv('Candidates.csv',index=False)